apiVersion: v1
kind: ConfigMap
metadata:
  name: mv-objects-dev-config
  namespace: wrld3d
  labels:
    app: mv-objects-dev
    tier: wrld3d
data:
  DATABASE_URL: <DATABASE_URL>
  DEV_DATABASE_URL: <DEV_DATABASE_URL>
  NODE_ENV: <NODE_ENV>
  APP_PORT: <APP_PORT>
  CRYPT_KEY: <CRYPT_KEY>
  MV_AUTH_URL: <MV_AUTH_URL>
  INFURA_BLOCK_CHAIN_URL: <INFURA_BLOCK_CHAIN_URL>
  BASE_URL: <AWS_BASE_URL>
  AWS_BUCKET_NAME: <AWS_BUCKET_NAME>
  AWS_BUCKET_REGION: <AWS_BUCKET_REGION>
  AWS_ACCESS_KEY: <AWS_ACCESS_KEY>
  AWS_SECRET_KEY: <AWS_SECRET_KEY>
  MINT_WALLET_ADDRESS: <MINT_WALLET_ADDRESS>
  MINT_WALLET_PRIVATE_KEY: <MINT_WALLET_PRIVATE_KEY>
  REDIS_URL: <REDIS_URL>
  BLOCK_CHAIN_API_URL: <BLOCK_CHAIN_API_URL>
  IPFS_NODE_URL: <IPFS_NODE_URL>
  IPFS_GET_URL: <IPFS_GET_URL>
  MV_PLAYER_URL: <MV_PLAYER_URL>
  HTTP_CLIENT_TIMEOUT: <HTTP_CLIENT_TIMEOUT>
  PINATA_API_KEY: <PINATA_API_KEY>
  PINATA_API_SECRET: <PINATA_API_SECRET>
  PINATA_PIN_JSON_URL: <PINATA_PIN_JSON_URL>
  PINATA_GET_URL: <PINATA_GET_URL>
  PINATA_PIN_FILE_URL: <PINATA_PIN_FILE_URL>
