apiVersion: v1
kind: Service
metadata:
  name: mv-objects-service
  namespace: wrld3d
spec:
  type: NodePort
  selector:
    app: mv-objects-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
