apiVersion: v1
kind: Service
metadata:
  name: mv-objects-dev-service
  namespace: wrld3d
spec:
  type: NodePort
  selector:
    app: mv-objects-dev-service
  ports:
    - protocol: TCP
      port: 8101
      targetPort: 8101
